### ISSUE TITLE
Key error when building the dataset

### ISSUE THREAD

**Issue by qiuwei** [timeseriesAI/timeseriesAI#13]
I was building my own dataset according to the tutorial but encountered the following error:

```
(26994, 27, 100) (26994,) ((#22495) [0,1,2,3,4,5,6,7,8,9...], (#4499) [22495,22496,22497,22498,22499,22500,22501,22502,22503,22504...])
Traceback (most recent call last):
  File "train2.py", line 16, in <module>
    dsets = TSDatasets(X, y, tfms=tfms, splits=splits, inplace=True)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/src/tsai/tsai/data/core.py", line 159, in __init__
    self.ptls = L([tl if not self.inplace else tl[:] if type(tl[0]).__name__ == 'memmap' else tensor(stack(tl[:])) for tl in self.tls])
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/src/tsai/tsai/data/core.py", line 159, in <listcomp>
    self.ptls = L([tl if not self.inplace else tl[:] if type(tl[0]).__name__ == 'memmap' else tensor(stack(tl[:])) for tl in self.tls])
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastai2/data/core.py", line 266, in __getitem__
    return self._after_item(res) if is_indexer(idx) else res.map(self._after_item)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastcore/foundation.py", line 377, in map
    return self._new(map(g, self))
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastcore/foundation.py", line 327, in _new
    def _new(self, items, *args, **kwargs): return type(self)(items, *args, use_list=None, **kwargs)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastcore/foundation.py", line 47, in __call__
    res = super().__call__(*((x,) + args), **kwargs)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastcore/foundation.py", line 318, in __init__
    items = list(items) if use_list else _listify(items)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastcore/foundation.py", line 254, in _listify
    if is_iter(o): return list(o)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastcore/foundation.py", line 220, in __call__
    return self.fn(*fargs, **kwargs)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastai2/data/core.py", line 229, in _after_item
    def _after_item(self, o): return self.tfms(o)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastcore/transform.py", line 187, in __call__
    def __call__(self, o): return compose_tfms(o, tfms=self.fs, split_idx=self.split_idx)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastcore/transform.py", line 140, in compose_tfms
    x = f(x, **kwargs)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastcore/transform.py", line 72, in __call__
    def __call__(self, x, **kwargs): return self._call('encodes', x, **kwargs)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastcore/transform.py", line 82, in _call
    return self._do_call(getattr(self, fn), x, **kwargs)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastcore/transform.py", line 86, in _do_call
    return x if f is None else retain_type(f(x, **kwargs), x, f.returns_none(x))
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastcore/dispatch.py", line 98, in __call__
    return f(*args, **kwargs)
  File "/home/wqiu/.cache/pypoetry/virtualenvs/dzts-kaskTdXw-py3.7/lib/python3.7/site-packages/fastai2/data/transforms.py", line 228, in encodes
    def encodes(self, o): return TensorCategory(self.vocab.o2i[o])
KeyError: -0.040000000000000036
```

**Comment by qiuwei** [comment]
It turns out to be some problem with my preprocess. Some Y labels in the test set do not present in the training set.

**Comment by miladalipour99** [comment]
Hello 
I am going to building the data with with my on dataset.
would you mind to advice me which notebooks are applicable for you in this issue?
thank you
